### PR TITLE
Executor test script

### PR DESCRIPTION
**Pull request by jychoi-hpc**
Add a script to test various future execuators; ProcessPoolExecutor, ThreadPoolExecutor, MPICommExecutor, MPIPoolExecutor

### CODE REVIEW

**Comment by jychoi-hpc** [comment]
This is only a single file (`test_executor.py`). 
I was not intended to use in a unit test though. I am wondering if there is any good place to put this.

**Comment by rkube** [comment]
pytest automatically executes this when this is put in the test folder, causing the unit tests to report as failed. Can you modify the pytest configuration such that it excludes this file when running the tests?

**Comment by jychoi-hpc** [comment]
Thanks for the tip. I put a line to ignore the file.

**Comment by rkube** [comment]
👍

**Pull request merged**
